name: Convert formats - bomctl

on:
  push:
    branches:
      - 'main'

jobs:
  sbom-download:
    runs-on: macos-latest

    steps:
      - name: Download SBOM from Github's Dependency Graph
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/dependency-graph/sbom \
            > sbom_spdx.json

      - name: Install conversion tool
        run: |
            brew tap bomctl/bomctl && brew install bomctl

    # the import of the SBOM errors out
      - name: Convert to CycloneDX
        run: |
            bomctl import sbom_spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom