name: Download Dependency Graph SBOM

on:
  push:
    branches:
      - 'main'
    # tags:
    #   - '*'  # Runs on any new tag push

jobs:
  sbom-download:
    runs-on: ubuntu-latest

    steps:
      - name: Download SBOM
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/dependency-graph/sbom \
            > sbom_spdx.json

      - name: Install conversion tool
        run: |
            CYCLONEDXCLI_LATEST_URL=`curl -s https://api.github.com/repos/CycloneDX/cyclonedx-cli/releases/latest | jq -r '.assets[] | select(.name | contains ("-linux-x64")) | .browser_download_url' | grep -v md5`
            mkdir -p /opt/cyclonedx-cli
            wget -q -O /opt/cyclonedx-cli/cyclonedx-cli ${CYCLONEDXCLI_LATEST_URL}
            chmod +x /opt/cyclonedx-cli/cyclonedx-cli
            ln -s /opt/cyclonedx-cli/cyclonedx-cli /usr/local/bin/cyclonedx-cli
            cyclonedx-cli -h

      - name: Convert to CycloneDX
        run: |
            cyclonedx-cli convert --input-file ./sbom_spdx.json --output-file sbom.json > sbom_cyclonedx.txt

      - name: Print CycloneDX SBOM
        run: |
            cat ./sbom_cyclonedx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom_spdx.json